import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';

void main() => runApp(const DomApp());

class User { String username; String displayName; String password; User(this.username,this.displayName,this.password); Map<String,dynamic> toJson()=>{'username':username,'displayName':displayName,'password':password}; static User fromJson(Map<String,dynamic> j)=>User(j['username'],j['displayName'],j['password']); }
class Chat { String id,name,message,time,avatar; int unread; bool pinned,isChannel; Chat(this.id,this.name,this.message,this.time,this.avatar,this.unread,{this.pinned=false,this.isChannel=false}); Map<String,dynamic> toJson()=>{'id':id,'name':name,'message':message,'time':time,'avatar':avatar,'unread':unread,'pinned':pinned,'isChannel':isChannel}; static Chat fromJson(Map<String,dynamic> j)=>Chat(j['id'],j['name'],j['message'],j['time'],j['avatar'],j['unread']??0,pinned:j['pinned']??false,isChannel:j['isChannel']??false); }
class DomMessage { String id,text,time; bool mine,edited,pinned; String? replyTo; Set<String> reactions; DomMessage(this.id,this.text,{required this.mine,this.time='сейчас',this.replyTo,this.edited=false,this.pinned=false,Set<String>? reactions}):reactions=reactions??{}; Map<String,dynamic> toJson()=>{'id':id,'text':text,'time':time,'mine':mine,'edited':edited,'pinned':pinned,'replyTo':replyTo,'reactions':reactions.toList()}; static DomMessage fromJson(Map<String,dynamic> j)=>DomMessage(j['id'],j['text'],mine:j['mine']??false,time:j['time']??'',edited:j['edited']??false,pinned:j['pinned']??false,replyTo:j['replyTo'],reactions:Set<String>.from(j['reactions']??[])); }

class DomStore {
  List<User> users=[]; List<Chat> chats=[]; Map<String,List<DomMessage>> messages={}; String? currentUser;
  File get file { final app=Platform.environment['APPDATA'] ?? Directory.systemTemp.path; final dir=Directory('$app\\DOM'); if(!dir.existsSync()) dir.createSync(recursive:true); return File('${dir.path}\\dom_data.json'); }
  Future<void> load() async { if(file.existsSync()){ try { final j=jsonDecode(await file.readAsString()); users=(j['users'] as List? ?? []).map((x)=>User.fromJson(Map<String,dynamic>.from(x))).toList(); chats=(j['chats'] as List? ?? []).map((x)=>Chat.fromJson(Map<String,dynamic>.from(x))).toList(); final mm=Map<String,dynamic>.from(j['messages']??{}); messages={for(final e in mm.entries)e.key:(e.value as List).map((x)=>DomMessage.fromJson(Map<String,dynamic>.from(x))).toList()}; currentUser=j['currentUser']; } catch(_){ } } if(users.isEmpty){ users=[User('demo','DOM User','1234')]; chats=[Chat('welcome','DOM News','Добро пожаловать в DOM','сейчас','D',1),Chat('team','Команда DOM','Обсуждение проекта','сегодня','D',0)]; messages={'welcome':[DomMessage('1','Добро пожаловать в DOM 1.3 🚀',mine:false)],'team':[DomMessage('2','Теперь здесь можно создавать каналы и управлять сообщениями.',mine:false)]}; await save(); } }
  Future<void> save() async { final j={'users':users.map((x)=>x.toJson()).toList(),'chats':chats.map((x)=>x.toJson()).toList(),'messages':messages.map((k,v)=>MapEntry(k,v.map((x)=>x.toJson()).toList())),'currentUser':currentUser}; await file.writeAsString(jsonEncode(j)); }
  User? get me { for(final u in users) if(u.username==currentUser)return u; return null; }
}

class DomApp extends StatefulWidget { const DomApp({super.key}); @override State<DomApp> createState()=>_DomAppState(); }
class _DomAppState extends State<DomApp>{ final store=DomStore(); bool ready=false,dark=false; @override void initState(){super.initState(); store.load().then((_){if(mounted)setState(()=>ready=true);});}
 @override Widget build(BuildContext context){ if(!ready)return const MaterialApp(home:Scaffold(body:Center(child:CircularProgressIndicator()))); return MaterialApp(title:'DOM',debugShowCheckedModeBanner:false,themeMode:dark?ThemeMode.dark:ThemeMode.light,theme:_theme(false),darkTheme:_theme(true),home:store.currentUser==null?AuthScreen(store:store,onChanged:(){setState((){});}):HomeScreen(store:store,onLogout:(){setState(()=>store.currentUser=null);store.save();},onTheme:(v)=>setState(()=>dark=v)); }
 ThemeData _theme(bool d)=>ThemeData(useMaterial3:true,brightness:d?Brightness.dark:Brightness.light,colorSchemeSeed:const Color(0xFF6C4DFF),scaffoldBackgroundColor:d?const Color(0xFF101114):const Color(0xFFF7F7FB),fontFamily:'Arial',inputDecorationTheme:InputDecorationTheme(filled:true,fillColor:d?const Color(0xFF1B1D22):Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(18),borderSide:BorderSide.none)),cardTheme:CardThemeData(elevation:0,color:d?const Color(0xFF191B20):Colors.white,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(18)))); }

class AuthScreen extends StatefulWidget{final DomStore store;final VoidCallback onChanged;const AuthScreen({super.key,required this.store,required this.onChanged});@override State<AuthScreen>createState()=>_AuthState();}
class _AuthState extends State<AuthScreen>{bool register=false;final login=TextEditingController(),pass=TextEditingController(),name=TextEditingController();String? error;
 void submit(){final u=login.text.trim().toLowerCase().replaceAll('@','');final p=pass.text;if(u.isEmpty||p.isEmpty){setState(()=>error='Заполни логин и пароль');return;}if(register){if(name.text.trim().isEmpty){setState(()=>error='Укажи имя');return;}if(widget.store.users.any((x)=>x.username==u)){setState(()=>error='Этот @username уже занят');return;}widget.store.users.add(User(u,name.text.trim(),p));}else{final found=widget.store.users.where((x)=>x.username==u&&x.password==p);if(found.isEmpty){setState(()=>error='Неверный @username или пароль');return;}}widget.store.currentUser=u;widget.store.save();widget.onChanged();}
 @override Widget build(BuildContext c)=>Scaffold(body:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:430),child:Padding(padding:const EdgeInsets.all(28),child:Card(child:Padding(padding:const EdgeInsets.all(26),child:Column(mainAxisSize:MainAxisSize.min,children:[const CircleAvatar(radius:34,child:Text('D',style:TextStyle(fontSize:32,fontWeight:FontWeight.bold))),const SizedBox(height:16),const Text('DOM',style:TextStyle(fontSize:30,fontWeight:FontWeight.w900)),const SizedBox(height:5),Text(register?'Создание аккаунта':'Вход в DOM'),const SizedBox(height:24),if(register)TextField(controller:name,decoration:const InputDecoration(labelText:'Имя')),if(register)const SizedBox(height:12),TextField(controller:login,decoration:const InputDecoration(labelText:'@username'),autofillHints:const [AutofillHints.username]),const SizedBox(height:12),TextField(controller:pass,obscureText:true,decoration:const InputDecoration(labelText:'Пароль')),if(error!=null)Padding(padding:const EdgeInsets.only(top:12),child:Text(error!,style:TextStyle(color:Theme.of(c).colorScheme.error))),const SizedBox(height:18),SizedBox(width:double.infinity,child:FilledButton(onPressed:submit,child:Text(register?'Создать аккаунт':'Войти'))),TextButton(onPressed:()=>setState((){register=!register;error=null;}),child:Text(register?'Уже есть аккаунт — войти':'Создать новый аккаунт'))])))))); }
}

class HomeScreen extends StatefulWidget{final DomStore store;final VoidCallback onLogout;final ValueChanged<bool> onTheme;const HomeScreen({super.key,required this.store,required this.onLogout,required this.onTheme});@override State<HomeScreen>createState()=>_HomeState();}
class _HomeState extends State<HomeScreen>{int tab=0;final search=TextEditingController();void refresh(){setState((){});widget.store.save();}void snack(String s)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));
 void createChannel(){final n=TextEditingController(),d=TextEditingController();showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('Создать канал'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'Название канала')),const SizedBox(height:10),TextField(controller:d,decoration:const InputDecoration(labelText:'Описание (необязательно)'))]),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Отмена')),FilledButton(onPressed:(){final name=n.text.trim();if(name.isEmpty)return;final id='channel_${DateTime.now().millisecondsSinceEpoch}';final c=Chat(id,name,d.text.trim().isEmpty?'Новый канал':d.text.trim(),'сейчас',name.substring(0,1).toUpperCase(),0,isChannel:true);widget.store.chats.insert(0,c);widget.store.messages[id]=[];Navigator.pop(context);refresh();openChat(c);},child:const Text('Создать'))]));}
 void newChat(){final u=TextEditingController();showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('Новый чат'),content:TextField(controller:u,decoration:const InputDecoration(hintText:'@username')),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Отмена')),FilledButton(onPressed:(){final x=u.text.trim().replaceAll('@','').toLowerCase();if(x.isEmpty)return;final found=widget.store.users.where((e)=>e.username==x);if(found.isEmpty){snack('Пользователь не найден');return;}final f=found.first;final c=Chat('user_$x',f.displayName,'Новый чат','сейчас',f.displayName.substring(0,1).toUpperCase(),0);if(!widget.store.chats.any((e)=>e.id==c.id))widget.store.chats.insert(0,c);widget.store.messages.putIfAbsent(c.id,()=>[]);Navigator.pop(context);refresh();openChat(c);},child:const Text('Открыть'))]));}
 void openChat(Chat c){Navigator.push(context,MaterialPageRoute(builder:(_)=>ChatPage(store:widget.store,chat:c))).then((_){setState((){});widget.store.save();});}
 @override Widget build(BuildContext context){final titles=['Чаты','Контакты','Звонки','Настройки'];return Scaffold(appBar:AppBar(title:Text(titles[tab],style:const TextStyle(fontWeight:FontWeight.w800)),actions:[if(tab==0)IconButton(onPressed:newChat,icon:const Icon(Icons.edit_square)),if(tab==0)PopupMenuButton<String>(onSelected:(v){if(v=='channel')createChannel();},itemBuilder:(_)=>const [PopupMenuItem(value:'channel',child:ListTile(leading:Icon(Icons.campaign_outlined),title:Text('Создать канал')))])]),body:IndexedStack(index:tab,children:[messages(),ContactsPage(onStartChat:openChat,users:widget.store.users),const CallsPage(),SettingsPage(onThemeChanged:widget.onTheme,onLogout:widget.onLogout)]),floatingActionButton:tab==0?FloatingActionButton(onPressed:createChannel,tooltip:'Создать канал',child:const Icon(Icons.campaign_outlined)):null,bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const[NavigationDestination(icon:Icon(Icons.chat_bubble_outline),selectedIcon:Icon(Icons.chat_bubble),label:'Чаты'),NavigationDestination(icon:Icon(Icons.people_outline),selectedIcon:Icon(Icons.people),label:'Контакты'),NavigationDestination(icon:Icon(Icons.call_outlined),selectedIcon:Icon(Icons.call),label:'Звонки'),NavigationDestination(icon:Icon(Icons.settings_outlined),selectedIcon:Icon(Icons.settings),label:'Настройки')]);}
 Widget messages(){final q=search.text.trim().toLowerCase();final list=widget.store.chats.where((c)=>q.isEmpty||c.name.toLowerCase().contains(q)||c.message.toLowerCase().contains(q)).toList();list.sort((a,b)=>(b.pinned?1:0).compareTo(a.pinned?1:0));return Column(children:[Padding(padding:const EdgeInsets.fromLTRB(16,4,16,12),child:TextField(controller:search,onChanged:(_)=>setState((){}),decoration:const InputDecoration(hintText:'Поиск в DOM',prefixIcon:Icon(Icons.search)))),Expanded(child:ListView.builder(itemCount:list.length,itemBuilder:(_,i){final c=list[i];return ListTile(contentPadding:const EdgeInsets.symmetric(horizontal:16,vertical:5),leading:CircleAvatar(radius:27,child:Text(c.avatar)),title:Row(children:[if(c.isChannel)const Padding(padding:EdgeInsets.only(right:5),child:Icon(Icons.campaign,size:17)),Flexible(child:Text(c.name,style:const TextStyle(fontWeight:FontWeight.w700))),if(c.pinned)const Padding(padding:EdgeInsets.only(left:6),child:Icon(Icons.push_pin,size:15))]),subtitle:Text(c.message,maxLines:1,overflow:TextOverflow.ellipsis),trailing:Text(c.time,style:Theme.of(context).textTheme.labelSmall),onTap:()=>openChat(c),onLongPress:(){setState(()=>c.pinned=!c.pinned);widget.store.save();}}))]);}
}

class ChatPage extends StatefulWidget{final DomStore store;final Chat chat;const ChatPage({super.key,required this.store,required this.chat});@override State<ChatPage>createState()=>_ChatState();}
class _ChatState extends State<ChatPage>{final controller=TextEditingController();DomMessage? reply;String? editingId;List<DomMessage> get messages=>widget.store.messages.putIfAbsent(widget.chat.id,()=>[]);void save(){widget.store.save();setState((){});}void send(){final v=controller.text.trim();if(v.isEmpty)return;setState((){if(editingId!=null){final m=messages.firstWhere((x)=>x.id==editingId);m.text=v;m.edited=true;editingId=null;}else{messages.add(DomMessage(DateTime.now().microsecondsSinceEpoch.toString(),v,mine:true,replyTo:reply?.text));}controller.clear();reply=null;widget.chat.message=v;widget.chat.time='сейчас';});widget.store.save();}
 void edit(DomMessage m){if(!m.mine)return;setState((){editingId=m.id;controller.text=m.text;controller.selection=TextSelection.collapsed(offset:controller.text.length);});}
 void delete(DomMessage m){showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('Удалить сообщение?'),content:const Text('Сообщение будет удалено только из этого устройства.'),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Отмена')),FilledButton(onPressed:(){messages.remove(m);Navigator.pop(context);save();},child:const Text('Удалить'))]));}
 void menu(DomMessage m){showModalBottomSheet(context:context,builder:(_)=>SafeArea(child:Wrap(children:[ListTile(leading:const Icon(Icons.reply),title:const Text('Ответить'),onTap:(){Navigator.pop(context);setState(()=>reply=m);}),if(m.mine)ListTile(leading:const Icon(Icons.edit_outlined),title:const Text('Редактировать'),onTap:(){Navigator.pop(context);edit(m);}),ListTile(leading:const Icon(Icons.push_pin_outlined),title:Text(m.pinned?'Открепить':'Закрепить'),onTap:(){m.pinned=!m.pinned;Navigator.pop(context);save();}),if(m.mine)ListTile(leading:const Icon(Icons.delete_outline),title:const Text('Удалить'),onTap:(){Navigator.pop(context);delete(m);})])));}
 @override Widget build(BuildContext context){return Scaffold(appBar:AppBar(title:Row(children:[CircleAvatar(child:Text(widget.chat.avatar)),const SizedBox(width:10),Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(widget.chat.name,style:const TextStyle(fontSize:17,fontWeight:FontWeight.w800)),Text(widget.chat.isChannel?'канал':'в сети',style:const TextStyle(fontSize:12))])])),body:Column(children:[Expanded(child:ListView.builder(padding:const EdgeInsets.all(14),itemCount:messages.length,itemBuilder:(_,i){final m=messages[i];return Align(alignment:m.mine?Alignment.centerRight:Alignment.centerLeft,child:GestureDetector(onLongPress:()=>menu(m),child:Container(margin:const EdgeInsets.only(bottom:8),padding:const EdgeInsets.symmetric(horizontal:14,vertical:10),constraints:const BoxConstraints(maxWidth:520),decoration:BoxDecoration(color:m.mine?Theme.of(context).colorScheme.primaryContainer:Theme.of(context).cardColor,borderRadius:BorderRadius.circular(18)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[if(m.replyTo!=null)Text('↳ ${m.replyTo}',maxLines:1,overflow:TextOverflow.ellipsis,style:Theme.of(context).textTheme.bodySmall),Text(m.text),const SizedBox(height:3),Text('${m.time}${m.edited?' · изменено':''}',style:Theme.of(context).textTheme.labelSmall)]))));})),if(reply!=null||editingId!=null)Container(padding:const EdgeInsets.symmetric(horizontal:12,vertical:7),child:Row(children:[Icon(editingId!=null?Icons.edit:Icons.reply,size:18),const SizedBox(width:7),Expanded(child:Text(editingId!=null?'Редактирование сообщения':reply!.text,maxLines:1,overflow:TextOverflow.ellipsis)),IconButton(onPressed:(){setState((){reply=null;editingId=null;controller.clear();});},icon:const Icon(Icons.close))])),SafeArea(child:Padding(padding:const EdgeInsets.fromLTRB(10,6,10,10),child:Row(children:[Expanded(child:TextField(controller:controller,onSubmitted:(_)=>send(),decoration:InputDecoration(hintText:editingId!=null?'Изменить сообщение':'Сообщение...',prefixIcon:const Icon(Icons.add_circle_outline)))),const SizedBox(width:8),IconButton.filled(onPressed:send,icon:Icon(editingId!=null?Icons.check:Icons.send))])))]));}
}

class ContactsPage extends StatelessWidget{final List<User> users;final ValueChanged<Chat> onStartChat;const ContactsPage({super.key,required this.users,required this.onStartChat});@override Widget build(BuildContext c)=>ListView(children:[for(final u in users)ListTile(leading:CircleAvatar(child:Text(u.displayName.substring(0,1).toUpperCase())),title:Text(u.displayName),subtitle:Text('@${u.username}'),trailing:IconButton(icon:const Icon(Icons.chat_outlined),onPressed:()=>onStartChat(Chat('user_${u.username}',u.displayName,'Новый чат','сейчас',u.displayName.substring(0,1).toUpperCase(),0))) ]);}
class CallsPage extends StatelessWidget{const CallsPage({super.key});@override Widget build(BuildContext c)=>const Center(child:Text('Звонки будут доступны с сервером DOM')) ;}
class SettingsPage extends StatelessWidget{final ValueChanged<bool> onTheme;final VoidCallback onLogout;const SettingsPage({super.key,required this.onTheme,required this.onLogout});@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:[Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.person)),title:const Text('Аккаунт'),subtitle:const Text('Настройки профиля и безопасности'))),const SizedBox(height:10),Card(child:SwitchListTile(value:Theme.of(c).brightness==Brightness.dark,onChanged:onTheme,title:const Text('Тёмная тема'),secondary:const Icon(Icons.dark_mode_outlined))),const SizedBox(height:10),Card(child:ListTile(leading:const Icon(Icons.system_update_outlined),title:const Text('Версия DOM 1.3.0'),subtitle:const Text('Обновление готово к разработке'))),const SizedBox(height:10),Card(child:ListTile(leading:const Icon(Icons.logout,color:Colors.red),title:const Text('Выйти из аккаунта'),onTap:(){showDialog(context:c,builder:(_)=>AlertDialog(title:const Text('Выйти?'),content:const Text('Аккаунт останется сохранённым на этом компьютере.'),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Отмена')),FilledButton(onPressed:(){Navigator.pop(c);onLogout();},child:const Text('Выйти'))]));}))]);}
